# Generated by Django 3.2.9 on 2021-12-03 12:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('page_description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание для поисковых систем')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержимое')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор')),
                ('publication_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
            },
        ),
    ]
