# Generated by Django 3.2.9 on 2021-12-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
