# Generated by Django 3.2.9 on 2021-12-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_newsmodel_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
