# Generated by Django 3.2.9 on 2021-12-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newsmodel_short_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='short_content',
            field=models.TextField(verbose_name='Тизер'),
        ),
    ]
