# Generated by Django 3.2.9 on 2021-11-07 16:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPageModel',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('page_description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание для поисковых систем')),
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True, verbose_name='ID страницы')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержимое')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
            },
        ),
    ]
