# Generated by Django 3.2.9 on 2021-11-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0002_mainmenumodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenumodel',
            options={'verbose_name': 'Пункт главного меню', 'verbose_name_plural': 'Пункты главного меню'},
        ),
        migrations.RemoveField(
            model_name='mainmenumodel',
            name='link',
        ),
    ]
