# Generated by Django 3.2.9 on 2021-11-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0003_auto_20211108_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenumodel',
            name='page',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='static_pages.staticpagemodel', verbose_name='Страница'),
        ),
    ]
