# Generated by Django 3.2.9 on 2021-11-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0004_mainmenumodel_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenumodel',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='static_pages.staticpagemodel', verbose_name='Страница'),
        ),
    ]
