# Generated by Django 3.2.9 on 2021-11-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0005_alter_mainmenumodel_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenumodel',
            name='order',
            field=models.PositiveIntegerField(default=10, verbose_name='Позиция в списке'),
        ),
    ]
