# Generated by Django 3.2.9 on 2021-11-10 07:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0007_alter_mainmenumodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25, verbose_name='Заголовок блока')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержимое блока')),
            ],
            options={
                'verbose_name': 'Блок данных',
                'verbose_name_plural': 'Блоки данных',
                'ordering': ['label'],
            },
        ),
    ]
