# Generated by Django 3.2.9 on 2021-12-04 17:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0009_alter_contentblockmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpagemodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержимое'),
        ),
    ]
