# Generated by Django 3.2.9 on 2021-12-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0010_alter_staticpagemodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpagemodel',
            name='id',
            field=models.CharField(help_text='Зарезервированные id страниц (обязательно должны присутствовать): index - главная страница;             news - список новостей; articles - список статей; publications - список публикаций; services - услуги;             about - о нас; partners - партнеры; contacts - контакты.', max_length=25, primary_key=True, serialize=False, unique=True, verbose_name='ID страницы'),
        ),
    ]
