# Generated by Django 3.2.9 on 2021-12-09 06:42

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('page_description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание для поисковых систем')),
                ('header', models.CharField(max_length=255, verbose_name='Название')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='images/partners/', verbose_name='Логотип')),
                ('link_url', models.URLField(max_length=512, verbose_name='Ссылка (URL)')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['header'],
            },
        ),
    ]
