# Generated by Django 3.2.9 on 2021-12-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersmodel',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
