# Generated by Django 3.2.9 on 2021-12-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
    ]
