# Generated by Django 3.2.9 on 2021-12-07 15:03

import ckeditor_uploader.fields
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('page_description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание для поисковых систем')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('cover', easy_thumbnails.fields.ThumbnailerImageField(upload_to='images/articles/', verbose_name='Обложка статьи')),
                ('short_content', models.TextField(verbose_name='Тизер')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержимое')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='PublicationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('page_description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание для поисковых систем')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('cover', easy_thumbnails.fields.ThumbnailerImageField(upload_to='images/publications/', verbose_name='Обложка публикации')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержимое')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование источника')),
                ('source_url', models.URLField(max_length=512, verbose_name='URL')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-publication_date'],
            },
        ),
    ]
