# Generated by Django 3.2.9 on 2021-12-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationsmodel',
            name='content',
        ),
    ]
