# Generated by Django 3.2.9 on 2021-12-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_remove_publicationsmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationsmodel',
            name='source',
            field=models.CharField(max_length=255, verbose_name='Наименование источника'),
        ),
        migrations.AlterField(
            model_name='publicationsmodel',
            name='source_url',
            field=models.URLField(max_length=512, verbose_name='URL источника'),
        ),
    ]
