# Generated by Django 3.2.9 on 2021-12-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20211207_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationsmodel',
            name='publication_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
