# Generated by Django 3.2.9 on 2022-01-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publicationsmodel_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='pdf_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files/articles/%Y/%m', verbose_name='Файл pdf'),
        ),
    ]
