# Generated by Django 3.2.9 on 2022-01-31 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_alter_articlesmodel_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='video_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files/video/%Y/%m', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['avi', 'wmv', 'mov', 'mkv', '3gp', 'mpeg', 'mpeg-2', 'mpeg-4'])], verbose_name='Файл видео'),
        ),
    ]
